In [4]:
1+5

6

    SAmple Python Code

In [6]:
15> 10

True

In [8]:
num =15
name = 'Anna'
print("my number is {} and name is {}".format(num,name))

my number is 15 and name is Anna


In [14]:
s = 'abcdefgh'
s[0:4]

'abcd'

In [11]:
my_list = ['a','b','c','d','e']
          

In [12]:
my_list[1]

'b'

In [2]:
import numpy as np

In [3]:
myList = [1,2,3,4,5]
myList

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(myList)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5,5)

array([[0.64926541, 0.38464574, 0.95719485, 0.88868808, 0.5854249 ],
       [0.4049117 , 0.01740708, 0.12670035, 0.40352967, 0.76369508],
       [0.8521084 , 0.1166614 , 0.12344763, 0.87910603, 0.85230006],
       [0.26068789, 0.70654559, 0.09851428, 0.24768164, 0.13970933],
       [0.6443461 , 0.85272753, 0.42887009, 0.29631596, 0.1492337 ]])

In [30]:
np.random.randn(3,3)

array([[-1.12573597,  0.81578598, -1.59106147],
       [ 0.85522749, -0.44528634,  1.05451003],
       [ 1.27048147,  1.21134991,  0.36426114]])

In [34]:
np.random.randint(1,50,10)

array([39, 41, 41,  9, 43, 30, 24,  8, 31,  6])

In [39]:
arr= np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranarr = np.random.randint(0,50,10)
ranarr

array([22, 43, 47, 32, 42,  8, 33, 26, 13, 41])

In [55]:
ranarr.max()

47

In [56]:
ranarr.min()

8

In [57]:
ranarr.argmax()

2

In [58]:
ranarr.argmin()

5

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr.shape

(25,)

## 

In [64]:
arr2 = []

In [65]:
arr2

[]

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [75]:
arr[0:5] = 50

In [76]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
arr2 = arr

In [78]:
arr2

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
slice_of_arr = arr[0:9]

In [80]:
slice_of_arr[:] = 99

In [81]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
arr2

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
arr2 = arr.copy()

In [84]:
arr2 [:] = 10

In [85]:
arr2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10])

In [86]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
arr_2d = np.array([[2,4,6],[8,10,12],[14,16,18]])

In [89]:
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [90]:
arr_2d[2][2]

18

In [91]:
arr_2d[2,2]

18

In [95]:
arr_2d[:2,:2]

array([[ 2,  4],
       [ 8, 10]])

In [96]:
arr_2d[:2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [100]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [103]:
bool_arr = arr > 4

In [110]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [111]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [123]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr2 = np.arange(50)

In [130]:
arr2.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [131]:
arr2[:,3:5]

IndexError: too many indices for array

In [133]:
arr= np.arange(1,11)

In [134]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [136]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [138]:
arr+ 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [139]:
arr-100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [140]:
arr* 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [141]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [144]:
arr2 = arr**3

In [145]:
arr2.max()

1000

In [146]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [147]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [148]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [18]:
import pandas as pd

In [19]:
import numpy as np

# Series

In [3]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [6]:
labels

['a', 'b', 'c']

In [16]:
my_data

[10, 20, 30]

In [8]:
arr

array([10, 20, 30])

In [9]:
d

{'a': 10, 'b': 20, 'c': 30}

In [20]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [22]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [24]:
pd.Series(data= my_data,index = labels)

a    10
b    20
c    30
dtype: int64

In [25]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [27]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [30]:
ser1 = pd.Series([1,2,3,4],['USA','Japan','USSR','France'])

In [31]:
ser1

USA       1
Japan     2
USSR      3
France    4
dtype: int64

In [32]:
ser2 = pd.Series([1,2,3,5],['USA','Japan','USSR','Italy'])

In [34]:
ser2

USA      1
Japan    2
USSR     3
Italy    5
dtype: int64

In [35]:
ser1['USA']

1

In [37]:
ser1[2]

3

In [38]:
ser1 + ser2

France    NaN
Italy     NaN
Japan     4.0
USA       2.0
USSR      6.0
dtype: float64

# Data Frames

In [3]:
import numpy as np
import pandas as pd
from numpy. random import randn

In [41]:
np.random.seed(101)

In [4]:
df = pd.DataFrame(randn(5,5),['A','B','C','D','E'],['V','W','X','Y','Z'])

In [5]:
df

V         W         X         Y         Z
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [6]:
df['V']

A   -2.285776
B    0.265326
C   -0.627524
D   -0.019990
E   -1.539463
Name: V, dtype: float64

In [56]:
df[['W','V']]

W         V
A  1.407338 -0.568581
B -1.972605  1.028293
C -1.115710  1.606780
D -0.771329 -0.411055
E  0.358941  0.649148

In [7]:
df['new'] = df['W'] + df['V']

In [8]:
df['new']

A   -2.659237
B   -0.585493
C   -0.892894
D   -0.608439
E   -3.752991
Name: new, dtype: float64

In [9]:
df

V         W         X         Y         Z       new
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541 -2.659237
B  0.265326 -0.850819  0.058988  0.064132  0.469739 -0.585493
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846 -0.892894
D -0.019990 -0.588449  2.349996  0.118708 -0.071374 -0.608439
E -1.539463 -2.213528  1.028295  0.621648 -2.160348 -3.752991

In [10]:
df.drop('new',axis = 1)

V         W         X         Y         Z
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [11]:
df

V         W         X         Y         Z       new
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541 -2.659237
B  0.265326 -0.850819  0.058988  0.064132  0.469739 -0.585493
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846 -0.892894
D -0.019990 -0.588449  2.349996  0.118708 -0.071374 -0.608439
E -1.539463 -2.213528  1.028295  0.621648 -2.160348 -3.752991

In [13]:
df.drop('new',axis = 1,inplace = True)

In [14]:
df

V         W         X         Y         Z
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [15]:
df.drop('A')

V         W         X         Y         Z
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [16]:
df

V         W         X         Y         Z
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [18]:
df[['W','V']]

W         V
A -0.373462 -2.285776
B -0.850819  0.265326
C -0.265370 -0.627524
D -0.588449 -0.019990
E -2.213528 -1.539463

In [20]:
# Extract ROWS
df.loc['A']

V   -2.285776
W   -0.373462
X    0.489998
Y   -1.446473
Z   -2.885541
Name: A, dtype: float64

In [21]:
# Extract rows using index location
df.iloc[0]

V   -2.285776
W   -0.373462
X    0.489998
Y   -1.446473
Z   -2.885541
Name: A, dtype: float64

In [22]:
df.loc['B','W']

-0.8508190199822296

In [27]:
df.iloc[1,1]

-0.8508190199822296

In [28]:
df.loc[['A','B'],['V','W']]

V         W
A -2.285776 -0.373462
B  0.265326 -0.850819

In [31]:
df.iloc[[0,1],[0,1]]

V         W
A -2.285776 -0.373462
B  0.265326 -0.850819

In [32]:
df > 0

V      W     X      Y      Z
A  False  False  True  False  False
B   True  False  True   True   True
C  False  False  True  False  False
D  False  False  True   True  False
E  False  False  True   True  False

In [33]:
booldf = df > 0
booldf

V      W     X      Y      Z
A  False  False  True  False  False
B   True  False  True   True   True
C  False  False  True  False  False
D  False  False  True   True  False
E  False  False  True   True  False

In [34]:
df[booldf]

V   W         X         Y         Z
A       NaN NaN  0.489998       NaN       NaN
B  0.265326 NaN  0.058988  0.064132  0.469739
C       NaN NaN  1.047197       NaN       NaN
D       NaN NaN  2.349996  0.118708       NaN
E       NaN NaN  1.028295  0.621648       NaN

In [35]:
df[df> 0]

V   W         X         Y         Z
A       NaN NaN  0.489998       NaN       NaN
B  0.265326 NaN  0.058988  0.064132  0.469739
C       NaN NaN  1.047197       NaN       NaN
D       NaN NaN  2.349996  0.118708       NaN
E       NaN NaN  1.028295  0.621648       NaN

In [36]:
df['W'] > 0

A    False
B    False
C    False
D    False
E    False
Name: W, dtype: bool

In [38]:
df.loc['A'] > 0

V    False
W    False
X     True
Y    False
Z    False
Name: A, dtype: bool

In [39]:
df.iloc[0]> 0

V    False
W    False
X     True
Y    False
Z    False
Name: A, dtype: bool

In [40]:
df[df['W'] > 0]

Empty DataFrame
Columns: [V, W, X, Y, Z]
Index: []

In [41]:
df

V         W         X         Y         Z
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [43]:
df[df['V'] > 0]

V         W         X         Y         Z
B  0.265326 -0.850819  0.058988  0.064132  0.469739

In [44]:
df[df['Y'] > 0]

V         W         X         Y         Z
B  0.265326 -0.850819  0.058988  0.064132  0.469739
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [45]:
resultdf = df[df['Y'] > 0]
resultdf

V         W         X         Y         Z
B  0.265326 -0.850819  0.058988  0.064132  0.469739
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [46]:
resultdf['X']

B    0.058988
D    2.349996
E    1.028295
Name: X, dtype: float64

In [49]:
df[df['Y'] > 0][['V','X']]

V         X
B  0.265326  0.058988
D -0.019990  2.349996
E -1.539463  1.028295

In [50]:
df[(df['Y'] > 0) and df['Z'] > 0]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [52]:
df[(df['Y'] > 0) & (df['Z'] > 0)]   # AND operator

V         W         X         Y         Z
B  0.265326 -0.850819  0.058988  0.064132  0.469739

In [53]:
# OR operator
df[(df['Y'] > 0) | (df['Z'] > 0)]

V         W         X         Y         Z
B  0.265326 -0.850819  0.058988  0.064132  0.469739
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [54]:
df.reset_index()

index         V         W         X         Y         Z
0     A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
1     B  0.265326 -0.850819  0.058988  0.064132  0.469739
2     C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
3     D -0.019990 -0.588449  2.349996  0.118708 -0.071374
4     E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [55]:
df

V         W         X         Y         Z
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541
B  0.265326 -0.850819  0.058988  0.064132  0.469739
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846
D -0.019990 -0.588449  2.349996  0.118708 -0.071374
E -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [56]:
newind = 'CA NY OR AZ TX'.split()
newind

['CA', 'NY', 'OR', 'AZ', 'TX']

In [57]:
df['States'] = newind

In [58]:
df

V         W         X         Y         Z States
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541     CA
B  0.265326 -0.850819  0.058988  0.064132  0.469739     NY
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846     OR
D -0.019990 -0.588449  2.349996  0.118708 -0.071374     AZ
E -1.539463 -2.213528  1.028295  0.621648 -2.160348     TX

In [59]:
df.set_index('States')

V         W         X         Y         Z
States                                                  
CA     -2.285776 -0.373462  0.489998 -1.446473 -2.885541
NY      0.265326 -0.850819  0.058988  0.064132  0.469739
OR     -0.627524 -0.265370  1.047197 -0.270588 -1.046846
AZ     -0.019990 -0.588449  2.349996  0.118708 -0.071374
TX     -1.539463 -2.213528  1.028295  0.621648 -2.160348

In [60]:
df # if States need to replace the index permanently - then add 'arg 'inplace' = True

V         W         X         Y         Z States
A -2.285776 -0.373462  0.489998 -1.446473 -2.885541     CA
B  0.265326 -0.850819  0.058988  0.064132  0.469739     NY
C -0.627524 -0.265370  1.047197 -0.270588 -1.046846     OR
D -0.019990 -0.588449  2.349996  0.118708 -0.071374     AZ
E -1.539463 -2.213528  1.028295  0.621648 -2.160348     TX

# Multi-Index and Index Hierarchy
Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [62]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [65]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

A         B
G1 1  1.265253 -0.153161
   2  0.775090 -1.020493
   3 -1.573674  0.942798
G2 1 -0.028066 -0.397975
   2  2.060569 -1.021493
   3 -0.563282 -3.023295

In [66]:
df.loc['G1']

A         B
1  1.265253 -0.153161
2  0.775090 -1.020493
3 -1.573674  0.942798

In [69]:
df.loc['G1'].loc[1]

A    1.265253
B   -0.153161
Name: 1, dtype: float64

In [70]:
df.index.names = ['Groups','Num']

In [72]:
df.loc['G2'].loc[2]['B']

-1.0214929546678184

In [73]:
df.xs('G1', level = 'Groups')

A         B
Num                    
1    1.265253 -0.153161
2    0.775090 -1.020493
3   -1.573674  0.942798

In [74]:
df.xs(1, level = 'Num')

A         B
Groups                    
G1      1.265253 -0.153161
G2     -0.028066 -0.397975

MISSING Values

In [76]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [78]:
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [79]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [81]:
df.dropna(axis = 0) # droppign ROWS with NUll values

A    B  C
0  1.0  5.0  1

In [82]:
df.dropna(axis = 1) # droppign COLUMNS with NUll values

C
0  1
1  2
2  3

In [84]:
df.dropna(thresh = 2) # settign threshold for missing vlaue count

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [85]:
df.fillna(value = 'FILl VALUE')

A           B  C
0           1           5  1
1           2  FILl VALUE  2
2  FILl VALUE  FILl VALUE  3

In [86]:
df['A'].fillna(value = df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [87]:
df['B'].fillna(value = df['B'].mean())

0    5.0
1    5.0
2    5.0
Name: B, dtype: float64

In [88]:
df['B'].fillna(value = df['A'].mean())

0    5.0
1    1.5
2    1.5
Name: B, dtype: float64

In [ ]:
# GROUP BY

In [89]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

In [91]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [92]:
df.groupby('Company')

In [95]:
grpby = df.groupby('Company')
grpby.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [96]:
grpby.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [97]:
grpby.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [99]:
grpby.sum().loc['MSFT']

Sales    464
Name: MSFT, dtype: int64

In [100]:
df.groupby('Company').sum().loc['MSFT']

Sales    464
Name: MSFT, dtype: int64

In [101]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [102]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [103]:
df.groupby('Company').min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [104]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [105]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

# Merging,Concatenation etc

In [106]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [107]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [108]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [110]:
df1
df2
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [112]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [113]:
pd.concat([df1,df2,df3],axis = 1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [114]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})  

In [115]:
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [116]:
pd.merge(left,right,how = 'inner',on ='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [117]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [118]:
pd.merge(left,right,how = 'inner',on = ['key1','key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [120]:
pd.merge(left,right,how = 'outer',on = ['key1','key2'])

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [121]:
pd.merge(left,right,how = 'right',on = ['key1','key2'])

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

In [ ]:
## JOINING - to merge based on INDEX values

In [122]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [123]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [124]:
left.join(right,how = 'outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

# Operations

In [125]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})


In [127]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [128]:
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [130]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [132]:
len(df['col2'])

4

In [133]:
len(df['col2'].unique())

3

In [134]:
df['col2'].nunique()

3

In [135]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [136]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [140]:
df[df['col1']> 2]

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [141]:
df[(df['col1']> 2) & (df['col2'] == 444)]

col1  col2 col3
3     4   444  xyz

In [142]:
def times2(x):
    return x*2

In [143]:
df['col1'].sum()

10

In [144]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [146]:
df['col1'].apply(len)

TypeError: object of type 'int' has no len()

In [147]:
df['col1'].apply(lambda x: x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [148]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [149]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [153]:
df.sort_values(by='col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [154]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [155]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [156]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [157]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

# Data Input & Output

In [159]:
conda install sqlalchemy

SyntaxError: invalid syntax (<ipython-input-159-28f39036227c>, line 1)

In [160]:
pwd

'C:\\Users\\Sound1\\Documents\\Anna\\Python-DS-ML- Jose Portilla\\Docs\\Python-Data-Science-and-Machine-Learning-Bootcamp\\Python-Data-Science-and-Machine-Learning-Bootcamp'

In [190]:
df = pd.read_csv('example')

In [181]:
df.to_csv('My_output',index = 'false')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [187]:
pd.read_excel('Excel_Sample.xlsx',sheetname = 'Sheet2')

C:\Users\Sound1\Anaconda3\lib\site-packages\pandas\util\_decorators.py:118: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)


a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [188]:
df.to_excel('Excel_Sample2.xlsx',sheet_name = 'NewSheet')

In [191]:
data= pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [192]:
data

[                                             Bank Name                City  \
 0                  Washington Federal Bank for Savings             Chicago   
 1      The Farmers and Merchants State Bank of Argonia             Argonia   
 2                                  Fayette County Bank          Saint Elmo   
 3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 4                                       First NBC Bank         New Orleans   
 5                                        Proficio Bank  Cottonwood Heights   
 6                        Seaway Bank and Trust Company             Chicago   
 7                               Harvest Community Bank          Pennsville   
 8                                          Allied Bank            Mulberry   
 9                         The Woodbury Banking Company            Woodbury   
 10                              First CornerStone Bank     King of Prussia   
 11                                  Trust Company B

In [193]:
data[0]

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc

# SQL

In [205]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///: memory:')

In [198]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [204]:
#df.to_sql('my_table',engine)
df.to_sql('data', engine)

OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)

In [206]:
sql_df = pd.read_sql('data',con=engine)

OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)

In [207]:
sql_df

NameError: name 'sql_df' is not defined