In [4]:
1+5

6

    SAmple Python Code

In [6]:
15> 10

True

In [8]:
num =15
name = 'Anna'
print("my number is {} and name is {}".format(num,name))

my number is 15 and name is Anna


In [14]:
s = 'abcdefgh'
s[0:4]

'abcd'

In [11]:
my_list = ['a','b','c','d','e']
          

In [12]:
my_list[1]

'b'

In [2]:
import numpy as np

In [3]:
myList = [1,2,3,4,5]
myList

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(myList)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(5,5)

array([[0.64926541, 0.38464574, 0.95719485, 0.88868808, 0.5854249 ],
       [0.4049117 , 0.01740708, 0.12670035, 0.40352967, 0.76369508],
       [0.8521084 , 0.1166614 , 0.12344763, 0.87910603, 0.85230006],
       [0.26068789, 0.70654559, 0.09851428, 0.24768164, 0.13970933],
       [0.6443461 , 0.85272753, 0.42887009, 0.29631596, 0.1492337 ]])

In [30]:
np.random.randn(3,3)

array([[-1.12573597,  0.81578598, -1.59106147],
       [ 0.85522749, -0.44528634,  1.05451003],
       [ 1.27048147,  1.21134991,  0.36426114]])

In [34]:
np.random.randint(1,50,10)

array([39, 41, 41,  9, 43, 30, 24,  8, 31,  6])

In [39]:
arr= np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
ranarr = np.random.randint(0,50,10)
ranarr

array([22, 43, 47, 32, 42,  8, 33, 26, 13, 41])

In [55]:
ranarr.max()

47

In [56]:
ranarr.min()

8

In [57]:
ranarr.argmax()

2

In [58]:
ranarr.argmin()

5

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
arr.shape

(25,)

## 

In [64]:
arr2 = []

In [65]:
arr2

[]

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr[:15]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [75]:
arr[0:5] = 50

In [76]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [77]:
arr2 = arr

In [78]:
arr2

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
slice_of_arr = arr[0:9]

In [80]:
slice_of_arr[:] = 99

In [81]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
arr2

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
arr2 = arr.copy()

In [84]:
arr2 [:] = 10

In [85]:
arr2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10])

In [86]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
arr_2d = np.array([[2,4,6],[8,10,12],[14,16,18]])

In [89]:
arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [90]:
arr_2d[2][2]

18

In [91]:
arr_2d[2,2]

18

In [95]:
arr_2d[:2,:2]

array([[ 2,  4],
       [ 8, 10]])

In [96]:
arr_2d[:2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [100]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [103]:
bool_arr = arr > 4

In [110]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [111]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [106]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [123]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr2 = np.arange(50)

In [130]:
arr2.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [131]:
arr2[:,3:5]

IndexError: too many indices for array

In [133]:
arr= np.arange(1,11)

In [134]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [136]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [138]:
arr+ 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [139]:
arr-100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [140]:
arr* 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [141]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [144]:
arr2 = arr**3

In [145]:
arr2.max()

1000

In [146]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [147]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [148]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [18]:
import pandas as pd

In [19]:
import numpy as np

# Series

In [3]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [6]:
labels

['a', 'b', 'c']

In [16]:
my_data

[10, 20, 30]

In [8]:
arr

array([10, 20, 30])

In [9]:
d

{'a': 10, 'b': 20, 'c': 30}

In [20]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [22]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [24]:
pd.Series(data= my_data,index = labels)

a    10
b    20
c    30
dtype: int64

In [25]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [27]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [30]:
ser1 = pd.Series([1,2,3,4],['USA','Japan','USSR','France'])

In [31]:
ser1

USA       1
Japan     2
USSR      3
France    4
dtype: int64

In [32]:
ser2 = pd.Series([1,2,3,5],['USA','Japan','USSR','Italy'])

In [34]:
ser2

USA      1
Japan    2
USSR     3
Italy    5
dtype: int64

In [35]:
ser1['USA']

1

In [37]:
ser1[2]

3

In [38]:
ser1 + ser2

France    NaN
Italy     NaN
Japan     4.0
USA       2.0
USSR      6.0
dtype: float64

# Data Frames

In [39]:
import numpy as np
import pandas as pd
from numpy. random import randn

In [41]:
np.random.seed(101)

In [50]:
df = pd.DataFrame(randn(5,5),['A','B','C','D','E'],['V','W','X','Y','Z'])

In [51]:
df

V         W         X         Y         Z
A -0.568581  1.407338  0.641806 -0.905100 -0.391157
B  1.028293 -1.972605 -0.866885  0.720788 -1.223082
C  1.606780 -1.115710 -1.385379 -1.329660  0.041460
D -0.411055 -0.771329  0.110477 -0.804652  0.253548
E  0.649148  0.358941 -1.080471  0.902398  0.161781

In [52]:
df['V']

A   -0.568581
B    1.028293
C    1.606780
D   -0.411055
E    0.649148
Name: V, dtype: float64

In [56]:
df[['W','V']]

W         V
A  1.407338 -0.568581
B -1.972605  1.028293
C -1.115710  1.606780
D -0.771329 -0.411055
E  0.358941  0.649148

In [61]:
df['new'] = df['W'] + df['V']

In [62]:
df['new']

A    0.838757
B   -0.944312
C    0.491070
D   -1.182384
E    1.008088
Name: new, dtype: float64

In [63]:
df

V         W         X         Y         Z       new
A -0.568581  1.407338  0.641806 -0.905100 -0.391157  0.838757
B  1.028293 -1.972605 -0.866885  0.720788 -1.223082 -0.944312
C  1.606780 -1.115710 -1.385379 -1.329660  0.041460  0.491070
D -0.411055 -0.771329  0.110477 -0.804652  0.253548 -1.182384
E  0.649148  0.358941 -1.080471  0.902398  0.161781  1.008088

In [64]:
df.drop['new']

TypeError: 'method' object is not subscriptable